trigger:
 - main

pool:
 name: 'Default'

steps:
 - checkout: self

 - task: TerraformInstaller@1
   inputs:
    terraformVersion: 'latest'

 - script: |
    terraform init
    displayName: 'Terraform Init'

 - script: |
    terraform plan
    displayName: 'Terraform Plan'